### ISSUE TITLE
Patch file fails

### ISSUE THREAD

**Issue by stevekennedyuk** [wpscanteam/homebrew-tap#4]
patching file lib/wpscan/db/updater.rb
Hunk #1 FAILED at 24.
1 out of 1 hunk FAILED -- saving rejects to file lib/wpscan/db/updater.rb.rej

**Comment by erwanlr** [comment]
Downgraded to 3.8.18 until a proper fix is made. Will keep this issue open for it

**Comment by erwanlr** [comment]
Updated to 3.8.20 with the patch in wpscan :)
