### ISSUE TITLE
Patching from 3.8.15 -> 3.8.19 fails!

### ISSUE THREAD

**Issue by leviskualo** [wpscanteam/homebrew-tap#5]
==> Patching
==> Applying eed763944642416cb5245b4e0cd281cb161122b4.patch
patching file lib/wpscan/db/updater.rb
Hunk #1 FAILED at 24.
1 out of 1 hunk FAILED -- saving rejects to file lib/wpscan/db/updater.rb.rej

**Comment by sticksen** [comment]
same for me

**Comment by craigz-rtx** [comment]
myself as well.

**Comment by erwanlr** [comment]
Duplicate of https://github.com/wpscanteam/homebrew-tap/issues/4

FYI, I've just downgraded to 3.8.18 until a proper fix is made
